[[redirects]]
  from = "/src"
  to = "https://github.com/marcis-andersons/sliexnis/"
  status = 301
  force = false

[[redirects]]
  from = "/github"
  to = "https://github.com/MarcisAn/sliexnis/"
  status = 301
  force = false

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/rickastley/"
  status = 301
  force = false
